### ISSUE TITLE
Error in SMITE package tutorial

### ISSUE THREAD

**Issue by biovitus** [GreallyLab/SMITE#1]
Dear Sir/Madam,

I am getting error when executing makePvalueObject function from tutorial in SMITE package. I am enclosing the output of test_annotation and error I am getting. I like to know if you can help in fixing 
it.

Appreciate your help.

Sincerely,

biovitus

> test_annotation
> **\* Class P-Value Annotation, method Show **\* 
>  First 10 Expression data are shown: 
>          expression_effect expression_pvalue
> A1BG            0.31905997       0.835528104
> A1BG-AS1       -0.77446928       0.127105406
> A2M            -0.36049162       0.133665150
> A2M-AS1         0.34825637       0.004019176
> A2ML1           0.42322933       0.441982383
> A2MP1          -4.09733596       0.024239448
> A4GALT          0.05462111       0.376350339
> A4GNT          -0.08907314       0.190395073
> AA06            0.15552269       0.006156866
> AAAS           -0.01205622       0.087326870
>  First 10 rows of methylation  data are shown: 
> GRanges object with 10 ranges and 5 metadata columns:
>        seqnames               ranges strand |        name     feature    effect
>           <Rle>            <IRanges>  <Rle> | <character> <character> <numeric>
>   A1CF    chr10 [52588252, 52588253]      \* |        A1CF    original     2.049
>   A1CF    chr10 [52584012, 52584013]      \* |        A1CF    original   -12.668
>   A1CF    chr10 [52612663, 52612664]      \* |        A1CF    original     4.402
>   A1CF    chr10 [52582130, 52582131]      \* |        A1CF    original    31.446
>   A1CF    chr10 [52641045, 52641046]      \* |        A1CF    original    23.319
>   A1CF    chr10 [52631272, 52631273]      \* |        A1CF    original     0.220
>   A1CF    chr10 [52601040, 52601041]      \* |        A1CF    original    80.586
>   A1CF    chr10 [52588252, 52588253]      \* |        A1CF        body     2.049
>   A1CF    chr10 [52584012, 52584013]      \* |        A1CF        body   -12.668
>   A1CF    chr10 [52612663, 52612664]      \* |        A1CF        body     4.402
>              pval        type
>         <numeric> <character>
>   A1CF 0.17204032 methylation
>   A1CF 0.18500037 methylation
>   A1CF 0.08505655 methylation
>   A1CF 0.18568468 methylation
>   A1CF 0.03923139 methylation
>   A1CF 0.54036951 methylation
>   A1CF 0.26642095 methylation
>   A1CF 0.17204032 methylation
>   A1CF 0.18500037 methylation
>   A1CF 0.08505655 methylation
> ---
> 
>   seqinfo: 2 sequences from an unspecified genome; no seqlengths
> ******\* End Show (pvalue.object) ******\* 
> test_annotation <- makePvalueObject(test_annotation,
> - effect_directions = c(methylation_promoter = "decrease",
> - methylation_body = "decrease",
> - methylation_h3k4me1 = "bidirectional"))
>   Error in validObject(.Object) : 
>   invalid class “PvalueObject” object: invalid object for slot "genes" in class "PvalueObject": got class "factor", should be or extend class "character"

**Comment by radiohboy** [comment]
Hi,
    Thanks for contacting us.  The error indicates that dataset (even our test data) is being input as a factor instead of a character/numeric.  Can you verify that you used the options(stringsAsFactors=F) command before loading the data and using the package?  We are working on a better way to handle these factor-character issues for the release.

**Comment by biovitus** [comment]
Dear Sir,

Thank you for your reply. I did not use the options(stringsAsFactors=F) before using the package and loading the data. After using it I did not get the error mentioned in my initial comment.

Appreciate your help.

Sincerely,

biovitus

**Comment by radiohboy** [comment]
Great.  Yeah its an annoying issue but thats the only work-around that is reliable.  The program is part of the next Bioconductor release.  If you will be testing it on your data, we would love to know how your results look.  Please contact us with any general feedback through Github.
